[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.96.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.2", features = [] }
tauri-plugin-log = "2"
tauri-plugin-opener = "2.0.0"
tauri-specta = { version = "=2.0.0-rc.25", features = ["typescript"] }
specta = { version = "=2.0.0-rc.25", features = ["derive"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls-webpki-roots"] }
rss = { version = "2.0.13", features = ["serde"] }
thiserror = "2.0.18"
specta-typescript = "0.0.12"
nanoid = "0.5.0"
atom_syndication = "0.12.7"
ammonia = "4.1.2"
html2text = "0.17.1"
url = "2.5.8"
sea-orm = { version = "1.1.20", features = [ "sqlx-sqlite", "macros" ] }
