// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from '@tauri-apps/api/core';

/** Commands */
export const commands = {
	newFeed: (urlString: string) =>
		typedError<FeedWithArticles, FeedError>(
			__TAURI_INVOKE('new_feed', { urlString }),
		),
};

/* Types */
export type Article = {
	id: string;
	feed_id: string;
	guid: string;
	name: string | null;
	description: string | null;
	content: string | null;
	url: string | null;
	date: string | null;
	media_type: MediaType;
	enclosure: Enclosure | null;
	read: boolean;
	saved: boolean;
};

export type Enclosure = {
	url: string;
	mime_type: string | null;
	length: number;
};

export type Feed = {
	id: string;
	name: string;
	feed_type: FeedType;
	favourited: boolean;
	url: string;
	last_fetched: number;
};

export type FeedError = 'RequestFailed' | 'StreamFailed' | 'ParseFailed';

export type FeedType = 'rss' | 'atom';

export type FeedWithArticles = {
	feed: Feed;
	articles: Article[];
};

export type MediaType = 'text';

/* Tauri Specta runtime */
async function typedError<T, E>(
	result: Promise<T>,
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
	try {
		return { status: 'ok', data: await result };
	} catch (e) {
		if (e instanceof Error) throw e;
		return { status: 'error', error: e as any };
	}
}
