// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from '@tauri-apps/api/core';

/** Commands */
export const commands = {
	newFeed: (urlString: string) =>
		typedError<AddFeedResult, FeedError>(
			__TAURI_INVOKE('new_feed', { urlString }),
		),
	fetchFeeds: () =>
		typedError<Feed[], FeedError>(__TAURI_INVOKE('fetch_feeds')),
};

/* Types */
export type AddFeedResult = {
	feed: Feed;
	articles_light: ArticleLight[];
	articles_content: ArticleContent[];
};

export type ArticleContent = {
	id: string;
	content: string | null;
	enclosure_url: string | null;
	enclosure_mime_type: string | null;
	enclosure_length: number;
};

export type ArticleLight = {
	id: string;
	feed_id: string;
	article_guid: string;
	article_name: string | null;
	article_description: string | null;
	article_url: string | null;
	article_date: number;
	media_type: MediaType;
	article_read: boolean;
	article_saved: boolean;
};

export type Feed = {
	id: string;
	feed_name: string;
	feed_type: FeedType;
	favourited: boolean;
	feed_url: string;
	last_fetched: number;
};

export type FeedError =
	'RequestFailed' | 'StreamFailed' | 'ParseFailed' | 'DbFailed';

export type FeedType = 'rss' | 'atom';

export type MediaType = 'text';

/* Tauri Specta runtime */
async function typedError<T, E>(
	result: Promise<T>,
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
	try {
		return { status: 'ok', data: await result };
	} catch (e) {
		if (e instanceof Error) throw e;
		return { status: 'error', error: e as any };
	}
}
