// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	newFeed: (urlString: string) => typedError<AddFeedResult, FeedError>(__TAURI_INVOKE("new_feed", { urlString })),
	fetchFeeds: () => typedError<Feed[], FeedError>(__TAURI_INVOKE("fetch_feeds")),
	fetchFeed: (id: string) => typedError<Feed, FeedError>(__TAURI_INVOKE("fetch_feed", { id })),
	fetchArticleContent: (id: string) => typedError<[ArticleContent, Transcript | null], FeedError>(__TAURI_INVOKE("fetch_article_content", { id })),
	fetchArticlesLight: () => typedError<ArticleLight[], FeedError>(__TAURI_INVOKE("fetch_articles_light")),
	setStarFeed: (id: string, star: boolean) => typedError<null, FeedError>(__TAURI_INVOKE("set_star_feed", { id, star })),
	setSaveArticle: (id: string, save: boolean) => typedError<null, FeedError>(__TAURI_INVOKE("set_save_article", { id, save })),
	deleteFeed: (id: string) => typedError<null, FeedError>(__TAURI_INVOKE("delete_feed", { id })),
	refreshFeed: (id: string) => typedError<RefreshFeedResult, FeedError>(__TAURI_INVOKE("refresh_feed", { id })),
	refreshFeeds: () => typedError<RefreshFeedResult, FeedError>(__TAURI_INVOKE("refresh_feeds")),
};

/* Types */
export type AddFeedResult = {
	feed: Feed,
	new_count: number,
	articles_light: ArticleLight[],
};

export type ArticleContent = {
	id: string,
	content: string | null,
	enclosure_url: string | null,
	enclosure_mime_type: string | null,
	enclosure_length: number,
};

export type ArticleLight = {
	id: string,
	feed_id: string,
	article_guid: string,
	article_name: string | null,
	article_description: string | null,
	article_url: string | null,
	article_date: number,
	media_type: MediaType,
	article_read: boolean,
	article_saved: boolean,
};

export type Feed = {
	id: string,
	feed_name: string,
	feed_type: FeedType,
	favourited: boolean,
	feed_url: string,
	site_url: string | null,
	last_fetched: number,
};

export type FeedError = { type: "RequestFailed"; message: string } | { type: "StreamFailed"; message: string } | { type: "ParseFailed"; message: string } | { type: "DbError"; message: string } | { type: "AlreadySubscribed"; message: string } | { type: "TranscriptUnavailable"; message: string };

export type FeedType = "rss" | "atom" | "youtube";

export type MediaType = "text" | "video";

export type RefreshFeedResult = {
	new_count: number,
	articles_light: ArticleLight[],
};

export type Transcript = {
	id: string,
	article_id: string,
	video_id: string,
	lang: string,
	feed_type: FeedType,
	snippets: TranscriptSnippet[],
};

export type TranscriptSnippet = {
	text: string,
	start: number | null,
	duration: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

