name: Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch/tag/SHA to checkout'
        required: true
        default: 'main'

jobs:
  release-tauri:
    name: Tauri Release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'ubuntu-24.04-arm'
            args: ''
          - platform: 'ubuntu-latest'
            args: ''
            mobile: 'android'
          - platform: 'windows-latest'
            args: ''
          - platform: 'windows-latest'
            args: '--target i686-pc-windows-msvc --bundles nsis'
          - platform: 'windows-11-arm'
            args: ''

    runs-on: ${{ matrix.platform }}
    env:
      SQLX_OFFLINE: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.ref }}

      - name: Install Node.js 24
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ (matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin') || (matrix.mobile == 'android' && 'aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android') || (contains(matrix.args, 'i686-pc-windows-msvc') && 'i686-pc-windows-msvc') || '' }}

      # ANDROID
      - name: Set up JDK 17
        if: matrix.mobile == 'android'
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        if: matrix.mobile == 'android'
        uses: android-actions/setup-android@v4

      - name: Set up Android NDK
        if: matrix.mobile == 'android'
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r29
          link-to-sdk: true

      # SYSTEM
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: |
            ./src-tauri -> ../../target

      - name: Install dependencies (Ubuntu only)
        if: (matrix.platform == 'ubuntu-22.04' || matrix.platform == 'ubuntu-24.04-arm') && matrix.mobile == ''
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils

      - name: Install frontend dependencies
        run: npm ci

      - name: Set up Android signing
        if: matrix.mobile != ''
        run: |
          cd src-tauri/gen/android
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

      - name: Tauri build
        uses: tauri-apps/tauri-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: __VERSION__
          releaseName: 'Qration v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
          mobile: ${{ matrix.mobile }}